### ISSUE TITLE
Scroll hint in emoji selection

### ISSUE THREAD

**Issue by michellenebiolo** [todotoit/cryptoloji#100]
<img width="692" alt="screenshot 2016-03-03 12 29 14" src="https://cloud.githubusercontent.com/assets/9842076/13493379/1853ee9e-e13e-11e5-9cfb-c6ccb35c27b6.png">

**Comment by AmedeoSpagnolo** [comment]
fixed http://el.s.todo.to.it/cryptoloji/0704/#/encrypt
