### ISSUE TITLE
Make a no-logo version of the prototype

### ISSUE THREAD

**Issue by michellenebiolo** [todotoit/cryptoloji#103]
Mozilla needs a version of the prototype where the logo and Cryptoloji name in the copy are blocked out, in order to get approval on everything but that.
As soon as we have one iteration like this, let me know so I can share the specific link.

I say put a gray box over the logo and a [Website Name] in the copy, but do whatever is quickest/easiest/most effective :)

I highlighted in pink the copy where "Cryptoloji" appears at the moment, on the usual spreadsheet
https://docs.google.com/spreadsheets/d/1STrOHP3L2VmxmBqjIc3PPbJn0-tq5Qu2gOCgFTtXK_o/edit#gid=298121543

cc @Giorgio-Olivero, @abusedmedia

**Comment by michellenebiolo** [comment]
Update: the client is providing an alternative logo/name we can use.

**Comment by michellenebiolo** [comment]
The name to use is Cypholoji.
From Jordan:

> Here is our temporary stand-in logo to replace "cryptoloji" ... you can also rebuild build it to look like your current version, I love the rollover. 
> https://drive.google.com/file/d/0B2qu3ExKWIlvWTBiWFBGRF9QMTQ/view?usp=sharing
>

**Comment by AmedeoSpagnolo** [comment]
fixed at http://el.s.todo.to.it/cryptoloji/0742/

**Comment by michellenebiolo** [comment]
Mi sembra tutto ok, tranne il secondo step dell'onboarding (ma credo tu lo sapessi già).
Quando riesci a sistemare tutto con Cypholoji al posto di Cryptoloji lo condivido (per il resto del copy è un altro discorso).

**Comment by AmedeoSpagnolo** [comment]
fixed http://el.s.todo.to.it/cryptoloji/0746/#/onboarding/step2
