### ISSUE TITLE
Add visual hint for next step dots

### ISSUE THREAD

**Issue by michellenebiolo** [todotoit/cryptoloji#104]
![f6a0a63a-e155-11e5-8c98-7e65ddc03c66](https://cloud.githubusercontent.com/assets/9842076/13527110/0bb7732a-e20d-11e5-8182-9a37276b612b.png)

**Comment by Giorgio-Olivero** [comment]
in verità questo succede solo perchè non c'è ancora lo swipe attivo. se leggessero le ns note di release sarebbe piu' facile :)

**Comment by AmedeoSpagnolo** [comment]
non sarà possibile cliccare su quell'elemento per navigare l'omboarding
