### ISSUE TITLE
404 page 

### ISSUE THREAD

**Issue by Giorgio-Olivero** [todotoit/cryptoloji#119]
it's very nicely designed :)
on the desktop it needs some layout fixes
<img width="1067" alt="screenshot 2016-03-08 18 37 53" src="https://cloud.githubusercontent.com/assets/5148932/13611821/b3917212-e564-11e5-9df1-b2df8f846d87.png">

**Comment by abusedmedia** [comment]
It looks like the 404 state is within the onboarding main state

**Comment by endorama** [comment]
Layout problems are related to #122. Closing, please follow this issue there.
