### ISSUE TITLE
onboarding next btn position

### ISSUE THREAD

**Issue by abusedmedia** [todotoit/cryptoloji#121]
Need a better way to solve this layout issue on mobile device

![screenshot 2016-03-09 10 10 42](https://cloud.githubusercontent.com/assets/870788/13630360/46aabc3c-e5df-11e5-8410-0c1be78a9c1a.png)

**Comment by endorama** [comment]
Related to #122. Please follow this issue from there

**Comment by abusedmedia** [comment]
Is not the same issue, the btn must be there but with a correct layout management

**Comment by abusedmedia** [comment]
fixed
