### ISSUE TITLE
Share

### ISSUE THREAD

**Issue by abusedmedia** [todotoit/cryptoloji#142]
- [x] bubble under message
- [x] better and bigger font-size based on length and available space
- [x] modal ends before header
- [x] cropped 'copy' btn under iOS, move below the URL
- [x] better method to copy key under iOS
- [x] social link, open in blank window
- [x] close X with more padding on desktop
- [x] key panel already open on desktop
- [x] better space between elements
- [x] url color, different from mockup

**Comment by AmedeoSpagnolo** [comment]
@marcoaimo servirebbe calcolare l'altezza della pagina di share e il suo spostamento con js

**Comment by AmedeoSpagnolo** [comment]
closed http://el.s.todo.to.it/cryptoloji/1009/#/share
