### ISSUE TITLE
Onboarding last step

### ISSUE THREAD

**Issue by Giorgio-Olivero** [todotoit/cryptoloji#148]
- the speechbubble size with the '...' and the 'what' should have the same size, at lest in height but more likely also in width. without visible size change during the fade
- the text style of the gray bubble and the 'here's the key' should be the same. the one on blue looks heavier. is it only because it's on a darker background?

<img width="602" alt="screenshot 2016-03-19 17 04 37" src="https://cloud.githubusercontent.com/assets/5148932/13899699/ccd7c896-edf4-11e5-80c3-36b5954e9c63.png">
<img width="284" alt="screenshot 2016-03-19 17 04 17" src="https://cloud.githubusercontent.com/assets/5148932/13899697/ccd5e13e-edf4-11e5-8617-3c36d4426a89.png">
<img width="317" alt="screenshot 2016-03-19 17 04 12" src="https://cloud.githubusercontent.com/assets/5148932/13899698/ccd60402-edf4-11e5-8c1c-6a77be8ab2c7.png">

**Comment by Giorgio-Olivero** [comment]
text color of 'what' and 0got it' could be gray 80%

**Comment by abusedmedia** [comment]
font-style are the same, I suppose it's an optical effect and/or browser rendering differences (in any case something we cannot control)
