### ISSUE TITLE
Pre-defined text on sharing

### ISSUE THREAD

**Issue by Giorgio-Olivero** [todotoit/cryptoloji#149]
if I share the current website FB get's this info card:
<img width="232" alt="screenshot 2016-03-19 17 09 44" src="https://cloud.githubusercontent.com/assets/5148932/13899730/7efe3762-edf5-11e5-8101-a40f37f5d8c7.png">

we should design text and images.

**Comment by abusedmedia** [comment]
cc/ @michellenebiolo

**Comment by michellenebiolo** [comment]
Could it be simply "Cypholoji + A fun way to learn about ciphers" ?
Not sure what the max length is for these. 
I imagine we need something different for sharing an encrypted message, let me know.

**Comment by alemartina** [comment]
We can place that message and ask mozilla to provide the final one. We
should give the specs on the maxlenght for the different kind of sharings
and we should include in the message some emojis (the msg itself?)
We also need the sharing images for twitter and fb

On Tuesday, March 22, 2016, Michelle Nebiolo <notifications@github.com>
wrote:

> Could it be simply "Cypholoji + A fun way to learn about ciphers" ?
> Not sure what the max length is for these.
> I imagine we need something different for sharing an encrypted message,
> let me know.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/todotoit/cryptoloji/issues/149#issuecomment-199826783>
>


-- 
Sent from my phone

**Comment by abusedmedia** [comment]
Considering FB and TW cards only, we need:
- title
- description (200 chars max)
- website name and url
- image (size: 900x500 px)

**Comment by abusedmedia** [comment]
We cannot include the message itself of anything dynamic/generated since we are backend-less.

**Comment by abusedmedia** [comment]
To be fair, description length is for:
- Twitter: 200 chars
- Facebook: 300 chars

To me, they could be the same text... up to you

**Comment by michellenebiolo** [comment]
Some suggestions - let me know if any of these are viable:

**General website sharing:**
**Option A**
Title: Codemoji
Text: A fun tool to learn about ciphers
**Option B**
Title: Codemoji – A fun tool to learn about ciphers
Text: Codemoji teaches you about ciphers. Create and share messages with your friends using fun emoji.

**Sharing a scrambled message:**
Title: I have a message for you 😀
Text: I scrambled it with Codemoji, a fun tool to learn about ciphers

**Comment by abusedmedia** [comment]
Tags are in place, we still need to design the thumb image, closing this and opening a new one.
