### ISSUE TITLE
libraries and twemoji credits

### ISSUE THREAD

**Issue by Giorgio-Olivero** [todotoit/cryptoloji#150]
even if the twemoji license allows to use them without crediting it, as Mozilla is an organization devoted to opensource culture, it would be weird not to credit twemoji and moreover also all the open source libraries used in the project. this could be a link in the footer for the desktop version and a 3rd link in the mobile version.
doing this also will allow us to put TODO's name in the credits

**Comment by abusedmedia** [comment]
Right now we add the link without the page: Credits
@AmedeoSpagnolo can you make it?

**Comment by AmedeoSpagnolo** [comment]
added page and logic http://el.s.todo.to.it/cryptoloji/1011/#/credits
I need the contents of this section

**Comment by endorama** [comment]
There are plans to link this repository al well?

**Comment by Giorgio-Olivero** [comment]
yes also the link to our repo qwould be good.
edo can you make a list of the libraries and icon sets used? 
(even the one used for the social sharing buttons, everything)

**Comment by endorama** [comment]
@AmedeoSpagnolo can you please take on the icon set part? We need a list of all graphic assets that requires credits.

I'll post here the list

**Comment by endorama** [comment]
This is the list with links of all production dependencies of the application:

```
bowser (https://github.com/ded/bowser)
clipboard (https://github.com/zenorocha/clipboard.js)
cookie (https://github.com/florian/cookie.js)
esrever (https://github.com/mathiasbynens/esrever)
fastclick (https://github.com/ftlabs/fastclick)
fromcodepoint (https://mths.be/fromcodepoint)
gsap (https://github.com/greensock/GreenSock-JS)
jquery (https://github.com/jquery/jquery-dist)
jquery.transit (https://github.com/rstacruz/jquery.transit)
lodash (https://github.com/lodash/lodash)
nanoscroller (https://github.com/lodash/lodash)
normalize-css (https://github.com/necolas/normalize.css)
punycode (https://github.com/bestiejs/punycode.js)
rebound-js (https://github.com/facebook/rebound-js)
stateman (https://github.com/leeluolee/stateman)
theater (https://github.com/Zhouzi/TheaterJS)
twemoji (https://github.com/twitter/twemoji)
youarei (https://github.com/purge/youarei.js)
```

**Comment by AmedeoSpagnolo** [comment]
we only used assets from emoji twitter list or designed by us.
I think we do not need to credit anyone except twitter

**Comment by Giorgio-Olivero** [comment]
what about the social sharing icons?

**Comment by AmedeoSpagnolo** [comment]
@vanessa-poli gave me the icons

**Comment by Giorgio-Olivero** [comment]
@vanessa-poli any hints? ;-)

**Comment by vanessa-poli** [comment]
Twitter and Facebook icons are the ones used by Mozilla on the Encryption website. The one with the mail symbol on it were designed by us. @AmedeoSpagnolo could you update also that one using the same they use on the website to be more coherent?

**Comment by vanessa-poli** [comment]
![screen shot 2016-03-30 at 16 32 36](https://cloud.githubusercontent.com/assets/6576869/14145912/ff1dfcf4-f695-11e5-9263-b5a94c365e9c.png)
![screen shot 2016-03-30 at 16 32 27](https://cloud.githubusercontent.com/assets/6576869/14145913/ff1f0c84-f695-11e5-9d5c-3016aae209aa.png)
