### ISSUE TITLE
Encryption view - With some emoji encryption doesn't work

### ISSUE THREAD

**Issue by marcoaimo** [todotoit/cryptoloji#153]
With emoji 😡 as key the output is all 😀 instead of the proper encrypted output.

**Comment by endorama** [comment]
Unfortunately, the mentioned emoji unicode code point is a multiple of 547 ( which is the total number of emojis we use ) and this breaks this formula ( used in emoji alphabet generation ):
`(i * key) % EmojiList.length` (which will obviously return always 0 if `key` and `EmojiList.length` are multiple)

It seems that there are only 2 available solutions: rewriting the `Emojifier.generateEmojiListFrom` function or replacing this emoji.

Has been verified that this is the only emoji which has this problem.

**Comment by alemartina** [comment]
What's the issue about?

On Wednesday, March 23, 2016, Edoardo Tenani <notifications@github.com>
wrote:

> Unfortunately, the mentioned emoji unicode code point is a multiple of 547
> ( which is the total number of emojis we use ) and this breaks this formula
> ( used in emoji alphabet generation ):
> (i * key) % EmojiList.length (which will obviously return always 0 if key
> and EmojiList.length are multiple)
>
> It seems that there are only 2 available solutions: rewriting the
> Emojifier.generateEmojiListFrom function or replacing this emoji.
>
> Has been verified that this is the only emoji which has this problem.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/todotoit/cryptoloji/issues/153#issuecomment-200272109>
>


-- 
Sent from my phone

**Comment by endorama** [comment]
@AmedeoSpagnolo discussed this issue with me and proposed to try using the index of the emoji in the EmojiList instead of it's codepoint, but this lead to problems when the index is `0` or equal to the `EmojiList.length`.

**Comment by endorama** [comment]
I propose to replace the offending emoji as a solution, because:

- PR #159 is a nice implementation, but a bit obscure and needs some work
- we are sending them a blueprint of the current implementation, changing this would also require changing the blueprint
- this implementation is far more understandable and clear ( from a implementing code point of view ) than the one in #159, thus more respecting of the 'educational' scope of this work IMHO

I can identify a new emoji to replace this one.

**Comment by alemartina** [comment]
Ok

On Wednesday, March 23, 2016, Edoardo Tenani <notifications@github.com>
wrote:

> I propose to replace the offending emoji as a solution, because:
>
>    - PR #159 <https://github.com/todotoit/cryptoloji/pull/159> is a nice
>    implementation, but a bit obscure and needs some work
>    - we are sending them a blueprint of the current implementation,
>    changing this would also require changing the blueprint
>    - this implementation is far more understandable and clear ( from a
>    implementing code point of view ) than the one in #159
>    <https://github.com/todotoit/cryptoloji/pull/159>, thus more
>    respecting of the 'educational' scope of this work IMHO
>
> I can identify a new emoji to replace this one.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/todotoit/cryptoloji/issues/153#issuecomment-200348212>
>


-- 
Sent from my phone
