### ISSUE TITLE
social buttons sharing

### ISSUE THREAD

**Issue by Giorgio-Olivero** [todotoit/cryptoloji#156]
1. we should differentiate between the available buttons on mobile and desktop.
e.g. on desktop there should be no whatsapp
2. check that all the others button are working properly on every system, platform
3. note down specifications on how much text we can use to prepopulate the sharing text fields (i guess FB would alow for more text than twitter etc)

**Comment by abusedmedia** [comment]
assigning to @marcoaimo, please consider only the first two point, the last one is already in #149

**Comment by endorama** [comment]
Point 1 and 2 are being addressed in PR #162
