### ISSUE TITLE
Test on IE

### ISSUE THREAD

**Issue by abusedmedia** [todotoit/cryptoloji#158]

**Comment by marcoaimo** [comment]
report from ie 10+.
 - cypholoji header svg (in encryption and decryption states) has an inline style="height" that breaks header spacing.
 - same inline style breaks all onboarding svgs dimension
 - in onboarding.js a "Promise is not defined" error block "leave" state execution https://github.com/todotoit/cryptoloji/blob/0c99e4006bad2db81d736db75dd3fc12afa25e99/assets/js/states/onboarding.js#L70
 - rest is all good

**Comment by endorama** [comment]
About The promise error: on IE there is no support for native Promise
objects.

Stateman uses promises to handle enter/leave.

Solutions:

- find a polyfill working on IE 10/11
- use a library like Q
- try to use jquery promises ( that do not adhere to the A+ standard and
could not work )

On Wed, 23 Mar 2016 18:40 marco aimo, <notifications@github.com> wrote:

> report from ie 10+.
>
>    - cypholoji header svg (in encryption and decryption states) has an
>    inline style="height" that breaks header spacing.
>    - same inline style breaks all onboarding svgs dimension
>    - in onboarding.js a "Promise is not defined" error block "leave"
>    state execution
>    https://github.com/todotoit/cryptoloji/blob/0c99e4006bad2db81d736db75dd3fc12afa25e99/assets/js/states/onboarding.js#L70
>    - rest is all good
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/todotoit/cryptoloji/issues/158#issuecomment-200460556>
>
-- 
— Edoardo Tenani •
— TODO <http://todo.to.it/> • FB <https://www.facebook.com/todotoit> •
Twitter <https://twitter.com/todotoit> • Instagram
<https://instagram.com/todotoit>

**Comment by AmedeoSpagnolo** [comment]
closed
