### ISSUE TITLE
change balloon color in onboarding chat

### ISSUE THREAD

**Issue by michellenebiolo** [todotoit/cryptoloji#167]
@Giorgio-Olivero chiedeva di cambiare lo sfondo dei fumetti blu su sfondo blu scuro perché stacchino meglio.

**Comment by AmedeoSpagnolo** [comment]
fixed http://el.s.todo.to.it/cryptoloji/1105/share.html?data=eyJtZXNzYWdlIjoi8J%2BPg%2FCfmJDwn5Or8J%2BPgyIsImtleSI6IvCfmIEifQ%3D%3D
