### ISSUE TITLE
Update onboarding steps 6-7

### ISSUE THREAD

**Issue by michellenebiolo** [todotoit/cryptoloji#168]
Allo step 6 dell’onboarding va cambiata l’animazione (indicazioni sul deck condiviso da Mozilla, @abusedmedia dovrebbe sapere cosa va fatto) e messo “Next” invece di “Go for it!” perché si aggiunge uno step 7.

Stiamo aspettando ok sul copy definitivo (e potrebbe volerci un po') ma intanto per impostare gli step 6 e 7 potete prendere i copy provvisori al [solito spreadsheet](https://docs.google.com/spreadsheets/d/1STrOHP3L2VmxmBqjIc3PPbJn0-tq5Qu2gOCgFTtXK_o/edit#gid=298121543).

**Comment by abusedmedia** [comment]
Fixed here http://el.s.todo.to.it/cryptoloji/1051
