### ISSUE TITLE
Update copy for client review

### ISSUE THREAD

**Issue by michellenebiolo** [todotoit/cryptoloji#171]
Please check and update all according to column L on this spreadsheet:
https://docs.google.com/spreadsheets/d/1STrOHP3L2VmxmBqjIc3PPbJn0-tq5Qu2gOCgFTtXK_o/edit#gid=298121543

**Comment by endorama** [comment]
Closed by 5ad6d49

**Comment by michellenebiolo** [comment]
Please update onboarding too :)
