### ISSUE TITLE
Mail icon

### ISSUE THREAD

**Issue by abusedmedia** [todotoit/cryptoloji#173]
![screen shot 2016-03-30 at 16 32 36](https://cloud.githubusercontent.com/assets/6576869/14145912/ff1dfcf4-f695-11e5-9263-b5a94c365e9c.png)
![screen shot 2016-03-30 at 16 32 27](https://cloud.githubusercontent.com/assets/6576869/14145913/ff1f0c84-f695-11e5-9d5c-3016aae209aa.png)

**Comment by AmedeoSpagnolo** [comment]
fixed http://el.s.todo.to.it/cryptoloji/1107/#/share
