### ISSUE TITLE
Implement Credits page

### ISSUE THREAD

**Issue by michellenebiolo** [todotoit/cryptoloji#176]
Copy approved by Mozilla:
https://docs.google.com/document/d/1jrBg0-EhKtv0db3Lu0B8n9kvyNDIkddlMqZN8mSBbdA/edit

**Comment by abusedmedia** [comment]
@AmedeoSpagnolo, can you have a look?

**Comment by AmedeoSpagnolo** [comment]
http://el.s.todo.to.it/cryptoloji/1115/#/credits
