### ISSUE TITLE
"Learn more" link

### ISSUE THREAD

**Issue by michellenebiolo** [todotoit/cryptoloji#177]
Mozilla will build the "Learn more" page at a later date. 
Please link "Learn more about encryption" (in the footer) to https://teach.mozilla.org/encryption

**Comment by abusedmedia** [comment]
It should be already in place... @endorama

**Comment by abusedmedia** [comment]
@AmedeoSpagnolo please check if it's true, thanks....

**Comment by AmedeoSpagnolo** [comment]
the link is correct.  "Learn more about encryption" to https://teach.mozilla.org/encryption.
these are the screenshots
![screen shot 2016-04-07 at 16 56 46](https://cloud.githubusercontent.com/assets/11834926/14355767/7f03f840-fce2-11e5-9bed-24c349a2769a.png)
![screen shot 2016-04-07 at 16 59 12](https://cloud.githubusercontent.com/assets/11834926/14355768/7f05733c-fce2-11e5-86c7-0de4720afeb3.png)
