### ISSUE TITLE
Change footer

### ISSUE THREAD

**Issue by michellenebiolo** [todotoit/cryptoloji#182]
Please change footer: no copy, centered logo, same color as links (see image below).

<img width="848" alt="46595d98-0050-11e6-8078-7dcc8d1bc255" src="https://cloud.githubusercontent.com/assets/9842076/14494825/1c16aba6-018d-11e6-9ac3-7745de05cb16.png">

**Comment by AmedeoSpagnolo** [comment]
closed http://el.s.todo.to.it/cryptoloji/1119/#/welcome
