### ISSUE TITLE
Favicon 

### ISSUE THREAD

**Issue by Giorgio-Olivero** [todotoit/cryptoloji#21]
@vanessa-poli draw a favicon with the enhanced watermelon and send it to
@AmedeoSpagnolo to implement it

**Comment by endorama** [comment]
@vanessa-poli required dimensions are:

- [ ] favicon.png _16x16_
- [ ] favicon.png _32x32_
- [ ] favicon.png _96x96_
- [ ] favicon.png _192x192_

**Comment by vanessa-poli** [comment]
![favicon-16x16](https://cloud.githubusercontent.com/assets/6576869/13180024/0b20e842-d727-11e5-9f72-fc1136cf8f8b.png)
![favicon-32x32](https://cloud.githubusercontent.com/assets/6576869/13180025/0b366cc6-d727-11e5-8be1-1ae5294c8f4d.png)
![favicon-96x96](https://cloud.githubusercontent.com/assets/6576869/13180026/0b4312c8-d727-11e5-9975-4a8d3b4ba2cc.png)
![favicon-192x192](https://cloud.githubusercontent.com/assets/6576869/13180027/0b45fad8-d727-11e5-80d0-23bebd6ba04e.png)

**Comment by Giorgio-Olivero** [comment]
@endorama could you implement it by today at 6pm?

**Comment by Giorgio-Olivero** [comment]
ciao cari, il favicon ancora non è apparso. :)

**Comment by abusedmedia** [comment]
It is in place in the built version, trust me, closing it.
