### ISSUE TITLE
check automatic copy from webpage functionality

### ISSUE THREAD

**Issue by Giorgio-Olivero** [todotoit/cryptoloji#22]
urgent, to be checked asap

**Comment by endorama** [comment]
From my investigation _copy_ from webpages is supported on every browser ( see [caniuse](http://caniuse.com/#feat=clipboard) statistics ) **except on** Safari.

This means that on iOS devices we should provide a proper fallback.

Every browser implementation differs from the other, but using a library such as [clipboard.js](https://clipboardjs.com/) we could uniform their behaviours ( apart from Safari, which unfortunately does not support Flash nor Clipboard API )
