### ISSUE TITLE
Emoji list length should be a prime number

### ISSUE THREAD

**Issue by endorama** [todotoit/cryptoloji#23]
Due to the fact that we are using modular algebra to compute emoji subset used to encode strings we need the length of the emoji set to be a prime number.

The emoji list is currently 592 emoji long, the nearest prime number is 593.
We propose to add another emoji to the set in order to fulfill this requirement.

**Comment by Giorgio-Olivero** [comment]
sure. pick one.

**Comment by endorama** [comment]
@fabtoit In the latest master the emoji modal selector has all selected emojis. Could you please provide one more?

**Comment by endorama** [comment]
Until the final new emoji is chosen, we added the emoji 🌪 ( code point 127786 ).

**Comment by endorama** [comment]
Final list of 547 emojis has been chosen, please refer `emojiListBuilder/complete.html` for implementation
