### ISSUE TITLE
broken image icon - onboarding

### ISSUE THREAD

**Issue by Giorgio-Olivero** [todotoit/cryptoloji#35]
spesso vedo questo tipo di icona/flash broken image sfocata quando accedo all'onboarding
soprattutto sull'anguria iniziale, mentre carica.

<img width="735" alt="screenshot 2016-02-19 12 09 30" src="https://cloud.githubusercontent.com/assets/5148932/13174106/ce7004a2-d701-11e5-8e0a-3f03832ab5b4.png">

**Comment by abusedmedia** [comment]
It should be fixed in 0400 and later
