### ISSUE TITLE
Backend API review

### ISSUE THREAD

**Issue by Giorgio-Olivero** [todotoit/cryptoloji#39]
we need to make sure that early next week we'll review the backend API specs and add anything that wasn't documented yet (JS/HTML injection check and error messages communication handling, generation of FB/Twitter card image, etcetera)
I'd like to involve also LEVA

@endorama @abusedmedia @michellenebiolo

**Comment by Giorgio-Olivero** [comment]
@endorama can you share a copy of the API specs document with LEVA?

**Comment by abusedmedia** [comment]
It needs also the update part related to the captcha mechanism, @terminalia can help on it.

**Comment by Giorgio-Olivero** [comment]
Mozilla needs the quote by Wedneday or *latest* Thursday. @abusedmedia

**Comment by endorama** [comment]
The spec documentation has been updated to version 2.0.0 and shared with LEVA
