### ISSUE TITLE
Text input field - size/visibility issue

### ISSUE THREAD

**Issue by Giorgio-Olivero** [todotoit/cryptoloji#4]
Early users feedback:
"Content is super tight on the screen. Maybe we don't need to show the key here?"
"Maybe "pick a key" text could be inline with the emojis instead of above?"

Once the text input is selected, could we hide (momentarily, only while the user is typing) the top bar, the key selection and just show the input field?
@endorama @AmedeoSpagnolo @abusedmedia 

A couple of screenshots from Nexus 4 + iPhone 5
<img width="426" alt="14a5d142-d174-11e5-9a4a-30780fe449a3" src="https://cloud.githubusercontent.com/assets/5148932/13019318/05383ad2-d1cf-11e5-80a8-b1cb0eb63afb.png">
![39076e64-d16b-11e5-8bc1-ec7fe219b764](https://cloud.githubusercontent.com/assets/5148932/13019319/053aafec-d1cf-11e5-9cd5-5bba1249493e.png)

**Comment by endorama** [comment]
There are some progress going on about this, assigning to @AmedeoSpagnolo

**Comment by endorama** [comment]
Should have been fixed with commits 277f73bb5d5500e4c9c39e891c1ee19bc51bf441, 5daf1fb459f70fdd114f6d904748f6cc305b1b9e and 31602c0606108620f0ae9482784b821ae0397c40

Closing, feel free to reopen in problem persists

**Comment by endorama** [comment]
Should have been fixed with commits 277f73bb5d5500e4c9c39e891c1ee19bc51bf441, 5daf1fb459f70fdd114f6d904748f6cc305b1b9e and 31602c0606108620f0ae9482784b821ae0397c40

Closing, feel free to reopen in problem persists
