### ISSUE TITLE
Onboarding doesn't progress

### ISSUE THREAD

**Issue by cassiemc** [todotoit/cryptoloji#40]
For me, the http://el.s.todo.to.it/cryptoloji/0428/#/onboarding doesn't progress through the slideshow (it did in one of the first iterations I saw). It does the initial turn on the watermelon, then hangs – once it did run through the C animation. 

Also, once I realized it wasn't automatically progressing, I expected to be able to click on the slideshow happy face circles at the bottom. And when that didn't work I used the keyboard arrows, which also didn't work. 'Skip' did work.

I'm using Chrome mac Version 48.0.2564.109

**Comment by Giorgio-Olivero** [comment]
@cassiemc the prototype is meant to be mobile only. no desktop version yet. 🙃
let me know if it works on mobile
