### ISSUE TITLE
Adjust desktop margins

### ISSUE THREAD

**Issue by cassiemc** [todotoit/cryptoloji#41]
On desktop, the fields are nearly flush against the left hand side. Would consider centering them, as per the Cryptoloji logo and share button, or at the very least add some significant left padding.

![margins](https://cloud.githubusercontent.com/assets/1186326/13183525/3fcdebf2-d705-11e5-99d2-d54f67ce29e8.jpg)

**Comment by Giorgio-Olivero** [comment]
@cassiemc the prototype is meant to be mobile only. no desktop version yet. 🙃
 I shared the instructions/notes with Jordan.

**Comment by cassiemc** [comment]
Right, I see the note now. Will grab my phone :)

**Comment by Giorgio-Olivero** [comment]
:)
