### ISSUE TITLE
remove 'dark ' emojis from our list

### ISSUE THREAD

**Issue by Giorgio-Olivero** [todotoit/cryptoloji#43]
the colour of some of the Twitter emojis is very dark, 

e.g. the telephone receiver
http://emojipedia.org/twitter/twemoji-2.0/telephone-receiver/

they 'disappear' on the dark blue background so we should remove them from our list.

@michellenebiolo @fabtoit @vanessa-poli

**Comment by michellenebiolo** [comment]
@endorama Do we need to replace the dark emojis with other options, to maintain the same total number?

**Comment by Giorgio-Olivero** [comment]
nope. we just need to decrease to the next prime number I guess. We also need to remove the similar looking emojis (hourgalsses, guitar/violin/sun/etc)

**Comment by michellenebiolo** [comment]
Ok. We are waiting on @endorama to provide us with an easy-to-use list of emojis (on dark background) so one (or more) of us can work on removing dark and similar emojis.

**Comment by endorama** [comment]
The list has been uploaded to our basecamp, you can review it there.

Assigned to @Giorgio-Olivero, please assign to me when done for implementation.

**Comment by endorama** [comment]
Closed by b59893e55ab4012f04b4f19b30932db11ba5fafb
