### ISSUE TITLE
Desktop version - top bar

### ISSUE THREAD

**Issue by Giorgio-Olivero** [todotoit/cryptoloji#44]
I took a peek into the desktop prototype here
http://el.s.todo.to.it/cryptoloji/0434/#/encrypt
Would it be possible to have a header slightly taller and with more whitespace? 
Looks to narrow to me. Maybe we can also keep the 'the fun encryption tool' text.

@AmedeoSpagnolo @vanessa-poli @abusedmedia

**Comment by AmedeoSpagnolo** [comment]
ok
