### ISSUE TITLE
Char counter text

### ISSUE THREAD

**Issue by Giorgio-Olivero** [todotoit/cryptoloji#5]
1. we should display it at the same height of the title 'your message', so on the top but aligned right.  So we can maximize the screen real estate for the user's text. 
1. The 'counter' should be made visible only while the input thext is selected and the user keyboard is displayed
1. if I input text and then erase it the counter goes back to 399 and not 400
1. the "characters left" indicator goes into the negative when you use up your 400 max chars

@endorama @AmedeoSpagnolo

**Comment by endorama** [comment]
Already fixed in current master. closing.
