### ISSUE TITLE
Fallback when javascript is not enabled

### ISSUE THREAD

**Issue by endorama** [todotoit/cryptoloji#51]
If the user does not have javascript enabled the application breaks rendering a white empty page.

We should provide a simple text or image to inform the user about this.

**Comment by endorama** [comment]
@michellenebiolo Could you provide a micro copy that tells to user it needs to enable javascript to use the application?

**Comment by michellenebiolo** [comment]
Something like this?
"Please enable javascript in your browser to use and see Cryptoloji correctly."

(do you need something pointing to instruction to do this? e.g. "Click here if you need help figuring out how." )

**Comment by endorama** [comment]
I suppose we could link to some resource to help users without javascript enabled.

Assigning to @marcoaimo for implementation.
