### ISSUE TITLE
Trigger animation on input blur on mobile

### ISSUE THREAD

**Issue by endorama** [todotoit/cryptoloji#65]
Related to #60

We should trigger animation on input blur on mobile, so that when a key has already been selected before and the user is updating the input text the open keyboard does not hide the animation.

**Comment by endorama** [comment]
Currently there are some concern about this. On Android the keyboard closed via the physical Back button does not trigger the `blur` event on the input.

This actually prevents us from understanding when the user has closed the keyboard and we should proceed to animate the output text.

**Comment by Giorgio-Olivero** [comment]
can you further investigate if there are really no other workarounds on Android?

**Comment by endorama** [comment]
After further investigations we were not able to find a suitable workaround for this.

Technically speaking we can:

- force close the keyboard, triggering a `blur` event programmatically ( after a delay? )
- add a delay before performing the animation ( unrelated to keyboard status )

There is a possible hackish solution ( that should be properly explored ): check screen size when input element in on focus.
Screen size should change when the virtual keyboard opens or closes, and this could lead to detecting keyboard status. I define it hackish because will be tricky to get it right.
If we are able to detect the status, we could trigger the blur immediately after the keyboard is closed ( only on android ).  
Could we set this has a nice to have and implement one of the solutions mentioned above for now?

cc: @marcoaimo

**Comment by Giorgio-Olivero** [comment]
Re option 2 
would that work in this way?  the bluebox animation is triggered if
- the text field has received some new content 
- AND if there has been no text input for 'n' units of time?

**Comment by endorama** [comment]
Yes.

**Comment by Giorgio-Olivero** [comment]
ok let's try it - up to you to fine tune the delays
