### ISSUE TITLE
Onboarding, substitute SVGs with new ones with updated copy

### ISSUE THREAD

**Issue by Giorgio-Olivero** [todotoit/cryptoloji#73]
Even if it's not finalized, I replaced the copy for the 8 onboarding SVGs in order to check the effect on the mobile. I'm not attaching them as SVG is not supported by github isses as a file format (!), you'll get them by email. can you include them in the next commit?

**Comment by endorama** [comment]
You should be able to upload them directly into the repository, instead as
attachments in a issue.

There should be a 'file upload' button when you navigate repository
folders. :) we could take a look at it tomorrow anyway.

On Wed, 24 Feb 2016 21:22 Giorgio Olivero <notifications@github.com> wrote:

> Even if it's not finalized, I replaced the copy for the 8 onboarding SVGs
> in order to check the effect on the mobile. I'm not attaching them as SVG
> is not supported by github isses as a file format (!), you'll get them by
> email. can you include them in the next commit?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/todotoit/cryptoloji/issues/73>.
>
-- 
— Edoardo Tenani •
— TODO <http://todo.to.it/> • FB <https://www.facebook.com/todotoit> •
Twitter <https://twitter.com/todotoit> • Instagram
<https://instagram.com/todotoit>

**Comment by Giorgio-Olivero** [comment]
thanks - but I'd rather let you experts do the 'commit' :)

**Comment by michellenebiolo** [comment]
Hey @endorama, please consider the slightly updated copy [in this spreadsheet](https://docs.google.com/spreadsheets/d/1STrOHP3L2VmxmBqjIc3PPbJn0-tq5Qu2gOCgFTtXK_o/edit#gid=298121543)
Red background = text changed
Orange background = just remove final full stop
Let me know when done, thanks.
