### ISSUE TITLE
Main share button in encrypt view covers emoji selection

### ISSUE THREAD

**Issue by endorama** [todotoit/cryptoloji#75]
See screenshot. Is happening on Mozilla Firefox 44.0.2 on Ubuntu.

![selection_006](https://cloud.githubusercontent.com/assets/526307/13328823/18e94dc4-dbf1-11e5-8ee2-55333114de9e.png)

This prevents clicking on emoji in the key panel.

**Comment by endorama** [comment]
As reported in #83 this happens also on Chrome, and probably the same behaviour is present in every browser.

**Comment by AmedeoSpagnolo** [comment]
closed by 3aa6749
