### ISSUE TITLE
Bluebox parser and css class name, needs better sanity check

### ISSUE THREAD

**Issue by abusedmedia** [todotoit/cryptoloji#78]
Some chars are not being caught by the parser therefore, some extra chars (like punctuation) will become css class name which breaks jquery selection (e.g. class="bb_(" or class="bb_!")

**Comment by endorama** [comment]
This should already have been solved by eda02418c13e37e5709f6e9da5194ff0ab8d9fbc, can you confirm?

**Comment by abusedmedia** [comment]
Confirmed.
