### ISSUE TITLE
on iPad > portrait

### ISSUE THREAD

**Issue by abusedmedia** [todotoit/cryptoloji#82]
The view is the mobile view but the emoji selector is not scrollable (due the current emoji list is too short) therefore the 'plus' button cannot be reachable.

**Comment by endorama** [comment]
We could fix this after #13.

The proposed solution is to show a different number of emojis on mobile ( 10 ) and tablet ( 15/20 ) in order to force the correct behaviour.

**Comment by endorama** [comment]
In case a longer list is needed, these are the emoji to add:
😊, 🙊, 🍄, 😬, 💡, 💈, 💋, 💌, 💍, 👨, 🐬, 🎲, 🍝, 🌞, 🌊
