### ISSUE TITLE
Green Flash onloading

### ISSUE THREAD

**Issue by Giorgio-Olivero** [todotoit/cryptoloji#97]
can we change the greenflash onloading screen so that it has the dark blue colour?
this is a 'live' prototype shared with the client, these details that can (WILL) generate misunderstanding on our design generate lots of communication efforts... needed to explain to the client that it is just 'beta'. they will post on redpen, we will have to check and reply, and it adds up taking lot's of wasted project management time.

**Comment by abusedmedia** [comment]
The mentioned version (with the yellow screen) has not been shared with the client yet. They have a different url to check for their review.

**Comment by alemartina** [comment]
Technically it is. We told the client they can check for updates on the
main index directory

On Thursday, March 3, 2016, Fabio Franchino <notifications@github.com>
wrote:

> The mentioned version (with the yellow screen) has not been shared with
> the client yet. They have a different url to check for their review.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/todotoit/cryptoloji/issues/97#issuecomment-191722286>.
>


-- 
Sent from my phone

**Comment by abusedmedia** [comment]
Ok, good to know, changed the color now, so no more yellow on the latest release. 
If they can and want to check every iteration, they need to know they are automatic deploy, therefore they need to know also that some release might be broken in some way.
cc @michellenebiolo 

closing it.

**Comment by michellenebiolo** [comment]
Added that disclaimer to client's github.
