### ISSUE TITLE
Check this and all apostrophes

### ISSUE THREAD

**Issue by michellenebiolo** [todotoit/cryptoloji#99]
<img width="678" alt="screenshot 2016-03-03 12 26 15" src="https://cloud.githubusercontent.com/assets/9842076/13493365/f970bf52-e13d-11e5-9693-92060f5115b2.png">

**Comment by michellenebiolo** [comment]
Controllato - al momento è l'unico apostrofo che vedo!

**Comment by AmedeoSpagnolo** [comment]
fixed http://el.s.todo.to.it/cryptoloji/0668/#/onboarding/step8
